version: '3'
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ../data/jarvis:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jarvis

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: jarvis-rails
    command: bundle exec rake resque:work
    env_file:
      - jarvis.env
    depends_on:
      - db
      - redis

  scheduler:
    image: jarvis-rails
    command: bundle exec rake resque:scheduler
    env_file:
      - jarvis.env
    depends_on:
      - db
      - redis

  api:
    image: jarvis-rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - jarvis.env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis