version: '3'
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ../data/jarvis:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jarvis

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: jarvis-rails
    command: bundle exec rake resque:work
    env_file:
      - jarvis.env
    depends_on:
      - db
      - redis
    restart: on-failure:5

  scheduler:
    image: jarvis-rails
    command: bundle exec rake resque:scheduler
    env_file:
      - jarvis.env
    depends_on:
      - db
      - redis
    restart: on-failure:5 

  api:
    image: jarvis-rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - jarvis.env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  # proxy:
  #   image: nginx
  #   volumes:
  #    - ./website.template:/etc/nginx/conf.d/website.template
  #   ports:
  #    - "80:80"
  #   command: /bin/bash -c "envsubst < /etc/nginx/conf.d/website.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  #   depends_on:
  #     - api
