version: '3'
services:

  db:
    image: postgres:14.10
    ports:
      - 5432:5432
    volumes:
      - ../data/jarvis:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=jarvis
      - POSTGRES_DB=jarvis
      - POSTGRES_PASSWORD=jarvis

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    image: jarvis-rails
    command: bundle exec rake resque:work
    env_file:
      - jarvis.env
    depends_on:
      - db
      - redis
    restart: always

  scheduler:
    image: jarvis-rails
    command: bundle exec rake resque:scheduler
    env_file:
      - jarvis.env
    depends_on:
      - db
      - redis
    restart: always

  api:
    image: jarvis-rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - jarvis.env
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    restart: always
