AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/tasks/resque.rake"
    - "spec/**/*"
    - "script/**/*"
    - "test/**/*"

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
