AllCops:   
  Exclude:
    - 'config/**/*'
    - 'db/**/*'     
    - 'spec/**/*'     
    - 'script/**/*'

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/DateTime:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

