AllCops:
  NewCops: enable # Automatically enable new cops
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/tasks/resque.rake"
    - "spec/**/*"
    - "script/**/*"
    - "test/**/*"

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false #

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
