source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.1'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.4.4'
# Use Puma as the app server
gem 'puma', '~> 4.3'

gem 'rack-cors', require: 'rack/cors' # allow cors requests (good for local development against production server)

group :development, :test do
  gem 'pry'
end

# background jobs
gem 'resque'
gem 'resque-scheduler'

# app specific gems
gem 'paper_trail' # keep track of versioning
gem 'plaid' # communicate with plaid api
gem 'rest-client' # make http requests
gem 'skylight' # apm
