source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'pg', '~> 1.2'
gem 'rails', '~> 5.2.1'

# Use Puma as the app server
gem 'puma', '~> 3.12'

gem 'httparty', '0.18.1'
gem 'slack-ruby-client', '~> 2.4'
gem 'google-id-token', '~> 1.4.2'
gem 'google-apis-calendar_v3', '~> 0.45'
gem 'signet', '~> 0.17'
gem 'omniauth-google-oauth2', '~> 1.2'
gem 'omniauth-rails_csrf_protection', '~> 1.0'

gem 'rack-cors', '~> 1.0.5', require: 'rack/cors' # allow cors requests (good for local development against production server)

group :development, :test do
  gem 'pry', '~> 0.12.0'
end

# background jobs
gem 'resque', '~> 1.27.4'
gem 'resque-scheduler', '~> 4.3.1'

# app specific gems
gem 'paper_trail', '~> 10.2.0' # keep track of versioning
