source 'https://rubygems.org'

gem 'sinatra'

gem 'sinatra-activerecord'
gem 'rufus-scheduler'
gem 'thin'
gem 'rake'

gem 'mechanize'

gem 'activerecord'
gem 'mysql2'

gem 'google_drive'
gem 'rest-client'

gem 'pry'