finances_email:
  cron: "0 15 * * *"
  class: "FinancesReport"
  queue: high
  args:
  description: "Daily Email Finances Report"

finances_syncer:
  cron: "0 14 * * *"
  class: "SyncFinances"
  queue: high
  args:
  description: "Daily Sync Finances from Plaid and Analyze"

balances_syncer:
  cron: "30 14 * * *"
  class: "SyncBalancesDaily"
  queue: high
  args:
  description: "Daily Sync Balances from Plaid"

southwest_searcher:
  cron: "30 */3 * * *"
  class: "SouthwestRunner"
  queue: high
  args:
  description: "Southwest Search"

reddit_newsletter:
  cron: "0 14 * * 0"
  class: "RedditNewsletter"
  queue: high
  args:
  description: "Weekly Reddit Newsletter"

testing_resque:
  cron: "*/15 * * * *"
  class: "TestJobX"
  queue: test
  args:
  description: "This job queues testing jobs"
